flamingo:
  router:
    path: /en

# Configure the modules flamingoCommerceAdapterStandalone
flamingoCommerceAdapterStandalone:
  commercesearch:
    enableIndexing: true
    repositoryAdapter: bleve
  csvindexing:
    productCsvPath: "ressources/products/products_en.csv"
    categoryCsvPath: "ressources/products/categories.csv"
    locale: "en_GB"
    currency: "GBP"
