
flamingo:
  router:
    path: /en


# Configure the module flamingo-commerce-adapter-standalone
flamingo-commerce-adapter-standalone.csvCommerce.productCsvPath: "ressources/products/products.csv"
flamingo-commerce-adapter-standalone.csvCommerce.locale: "en_GB"
flamingo-commerce-adapter-standalone.csvCommerce.currency: "GBP"
flamingo-commerce-adapter-standalone.csvCommerce.allowedImageResizeParamaters: "500x,200x,700x,40x"
